### ISSUE TITLE
Insets issue on Android 15 + targetSdk 35

### ISSUE THREAD

**Issue by savelyevdm** [ITECOMMPAY/mobile-sdk-android-ui#10]
Hi! @AlexeyKhrameev 

Recently we've noticed that there is an issue while using PaymentPage with Android 15 and targeting SDK version 35. In this mode PaymentPage after entering card number and removing keyboard becomes lowered, with no ability to restore its size (see screenshot below):

https://github.com/user-attachments/assets/4890635a-ef20-4da2-bb32-82b19803e024

Looks like the problem arises because of edge-2-edge mode, enabled by default in android 15 and, thus, necessity to deal more closely with insets (when building page).

**Comment by AlexeyKhrameev** [comment]
@savelyevdm try 3.7.1 version

**Comment by savelyevdm** [comment]
@AlexeyKhrameev Thank you, it works!
