### ISSUE TITLE
Restore minSDK 21 support

### ISSUE THREAD

**Issue by savelyevdm** [ITECOMMPAY/mobile-sdk-android-ui#6]
Hi!

As of version 3.6.1 your app states that minSDK version is 21:
```
defaultConfig {
    minSdk = 21
    targetSdk = 34
```

But actually there is code that fails after 3DS code is entered into your form:
```
kotlin.NotImplementedError: An operation is not implemented: VERSION.SDK_INT < O
    at
com.paymentpage.msdk.ui.utils.extensions.StringExtensionsKt.paymentDateToPatternDate(StringExtensions.kt:19)
```

Problem originates to this code:
https://github.com/ITECOMMPAY/mobile-sdk-android-ui/blob/9ce3acbcdad58f8dafdda510fb58357f6b07409e/mobile-sdk-android-ui/src/main/java/com/paymentpage/msdk/ui/utils/extensions/StringExtensions.kt#L19
```
    val ldt: LocalDateTime = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        LocalDateTime.parse(this, DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZ"))
    } else {
        TODO("VERSION.SDK_INT < O")
    }
```
Could you, please, fix it in order to truly support minSDK 21.

**Comment by AlexeyKhrameev** [comment]
fixed at 3.6.4
